[[pigz]]
arch = "aarch64"
git-tree-sha1 = "8251a49bb15b3c7ebeb43b1fdf4cd0383e4742af"
libc = "glibc"
os = "linux"

    [[pigz.download]]
    sha256 = "adcef4b0435b21e4ddc59986007a700b12d7f742893f5ef0c058237b1fa2d5fd"
    url = "https://github.com/JuliaBinaryWrappers/pigz_jll.jl/releases/download/pigz-v2.5.0+0/pigz.v2.5.0.aarch64-linux-gnu.tar.gz"
[[pigz]]
arch = "aarch64"
git-tree-sha1 = "7ba2d02c88565e795a177c2c9d8ae2fc6e745426"
libc = "musl"
os = "linux"

    [[pigz.download]]
    sha256 = "060a3cbb6403ef9ebba75530f5ac78b2f14e9e14e161b2d6099abdcf6034fb59"
    url = "https://github.com/JuliaBinaryWrappers/pigz_jll.jl/releases/download/pigz-v2.5.0+0/pigz.v2.5.0.aarch64-linux-musl.tar.gz"
[[pigz]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7611d7b8e51d7a9765be533d188968f47b1883f6"
libc = "glibc"
os = "linux"

    [[pigz.download]]
    sha256 = "6a89177934f816ad57bd416c73018773df3cf4dcdae6640663a2161c2ce09f0a"
    url = "https://github.com/JuliaBinaryWrappers/pigz_jll.jl/releases/download/pigz-v2.5.0+0/pigz.v2.5.0.armv7l-linux-gnueabihf.tar.gz"
[[pigz]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "eea8be5444d46dd02024bdc474bab5da75c62c69"
libc = "musl"
os = "linux"

    [[pigz.download]]
    sha256 = "59abe919c404891b35372f1c971a7b228b3d131d6609597e4c98fff0b5254ff3"
    url = "https://github.com/JuliaBinaryWrappers/pigz_jll.jl/releases/download/pigz-v2.5.0+0/pigz.v2.5.0.armv7l-linux-musleabihf.tar.gz"
[[pigz]]
arch = "i686"
git-tree-sha1 = "3fc30d1cff179506704de1eee10e8bbe1a0af93b"
libc = "glibc"
os = "linux"

    [[pigz.download]]
    sha256 = "e8f29ea25c833ecf4e1161e10430b72ea06ea20dbb8ab3463d1000ec2751bf53"
    url = "https://github.com/JuliaBinaryWrappers/pigz_jll.jl/releases/download/pigz-v2.5.0+0/pigz.v2.5.0.i686-linux-gnu.tar.gz"
[[pigz]]
arch = "i686"
git-tree-sha1 = "0cfda228fcc1bbcdefba4a1297ae72a092b44b39"
libc = "musl"
os = "linux"

    [[pigz.download]]
    sha256 = "29c9de318707007aebffa26355204e16502395b85eed8e6707a4a3acea350534"
    url = "https://github.com/JuliaBinaryWrappers/pigz_jll.jl/releases/download/pigz-v2.5.0+0/pigz.v2.5.0.i686-linux-musl.tar.gz"
[[pigz]]
arch = "i686"
git-tree-sha1 = "85479b36583a2421fb05ccc3eaf213cf6352fcaf"
os = "windows"

    [[pigz.download]]
    sha256 = "97e19d5af2c7b1ef20f84daba1bdcf3510fd80328aed8b972507db7651b8e4c5"
    url = "https://github.com/JuliaBinaryWrappers/pigz_jll.jl/releases/download/pigz-v2.5.0+0/pigz.v2.5.0.i686-w64-mingw32.tar.gz"
[[pigz]]
arch = "powerpc64le"
git-tree-sha1 = "bcc7ae3fbd516d554db1b283c64907d19b50bbbb"
libc = "glibc"
os = "linux"

    [[pigz.download]]
    sha256 = "77ed43d4b3dc64ad585cd4c01d82b31b9483c56b88d2d5289c7a47e53ca9b14f"
    url = "https://github.com/JuliaBinaryWrappers/pigz_jll.jl/releases/download/pigz-v2.5.0+0/pigz.v2.5.0.powerpc64le-linux-gnu.tar.gz"
[[pigz]]
arch = "x86_64"
git-tree-sha1 = "b55a70b17de1c2648f02a81b50ff96e3f78d8cdb"
os = "macos"

    [[pigz.download]]
    sha256 = "705b064701a09ae1e287e6bb28fbc16951b0a4fb7fa700531fbe92be9b5101cc"
    url = "https://github.com/JuliaBinaryWrappers/pigz_jll.jl/releases/download/pigz-v2.5.0+0/pigz.v2.5.0.x86_64-apple-darwin.tar.gz"
[[pigz]]
arch = "x86_64"
git-tree-sha1 = "4240f2211656b0d49bf74df913befc446ac99bf0"
libc = "glibc"
os = "linux"

    [[pigz.download]]
    sha256 = "84c2be53ab7d0590991f6b9066dea6fce166c34e83199d4151247c47b1cb9983"
    url = "https://github.com/JuliaBinaryWrappers/pigz_jll.jl/releases/download/pigz-v2.5.0+0/pigz.v2.5.0.x86_64-linux-gnu.tar.gz"
[[pigz]]
arch = "x86_64"
git-tree-sha1 = "dc5486e10247a9615445fb9b034bd4512f536727"
libc = "musl"
os = "linux"

    [[pigz.download]]
    sha256 = "21109aa4585f7d0335662277eb5fe606f8827727dcf9c6aeb4fefe314e72b9ee"
    url = "https://github.com/JuliaBinaryWrappers/pigz_jll.jl/releases/download/pigz-v2.5.0+0/pigz.v2.5.0.x86_64-linux-musl.tar.gz"
[[pigz]]
arch = "x86_64"
git-tree-sha1 = "bea93056a337dc6cd5631096f754b74a543d598b"
os = "freebsd"

    [[pigz.download]]
    sha256 = "0646e6ef16db60a7394321949fe159099d5ba13a0269ebb286684f5f31544da8"
    url = "https://github.com/JuliaBinaryWrappers/pigz_jll.jl/releases/download/pigz-v2.5.0+0/pigz.v2.5.0.x86_64-unknown-freebsd.tar.gz"
[[pigz]]
arch = "x86_64"
git-tree-sha1 = "b5eb68b0677d5c18a4552fc89094b31849bdf388"
os = "windows"

    [[pigz.download]]
    sha256 = "6185bc1be7688814ebe1a8359231a9677dde761f5f61abb3a6776b435c217d75"
    url = "https://github.com/JuliaBinaryWrappers/pigz_jll.jl/releases/download/pigz-v2.5.0+0/pigz.v2.5.0.x86_64-w64-mingw32.tar.gz"
