[[pigz]]
arch = "aarch64"
git-tree-sha1 = "2523fc0d123bc97107e66604eaad060e73bdc8c6"
os = "macos"

    [[pigz.download]]
    sha256 = "cb7bd29e445cffba9a0aad4590f935bd21a46fdc0df84411e7523f84579de6f0"
    url = "https://github.com/JuliaBinaryWrappers/pigz_jll.jl/releases/download/pigz-v2.7.0+0/pigz.v2.7.0.aarch64-apple-darwin.tar.gz"
[[pigz]]
arch = "aarch64"
git-tree-sha1 = "60a4bfe6310023b9681c99fe8e1838436c1cb60e"
libc = "glibc"
os = "linux"

    [[pigz.download]]
    sha256 = "3bf4474936fda7cb6183e242e009a957a8a3d3bbeaab4969612767a0351c60a9"
    url = "https://github.com/JuliaBinaryWrappers/pigz_jll.jl/releases/download/pigz-v2.7.0+0/pigz.v2.7.0.aarch64-linux-gnu.tar.gz"
[[pigz]]
arch = "aarch64"
git-tree-sha1 = "ecba35ff4b0dc2e1dbba9ba14b8806bc1ecee5ae"
libc = "musl"
os = "linux"

    [[pigz.download]]
    sha256 = "a0ee08832c055bff1861b791b3c4636e4fb179d24ac16113d49ecfc819670a05"
    url = "https://github.com/JuliaBinaryWrappers/pigz_jll.jl/releases/download/pigz-v2.7.0+0/pigz.v2.7.0.aarch64-linux-musl.tar.gz"
[[pigz]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ed20533872037ce26c03375d8d942f1eb616377d"
libc = "glibc"
os = "linux"

    [[pigz.download]]
    sha256 = "9004ed8a18bf1d4fb1369deb9eb8b47fac6dac7a44d5dba165b5ada5d8ab1896"
    url = "https://github.com/JuliaBinaryWrappers/pigz_jll.jl/releases/download/pigz-v2.7.0+0/pigz.v2.7.0.armv6l-linux-gnueabihf.tar.gz"
[[pigz]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "2bbad5d3f7f38543b0aaa0ac35555aa468d718e5"
libc = "musl"
os = "linux"

    [[pigz.download]]
    sha256 = "035225eae3972bb379bf37587986732849805f43b392e0e18f9502b8b2205416"
    url = "https://github.com/JuliaBinaryWrappers/pigz_jll.jl/releases/download/pigz-v2.7.0+0/pigz.v2.7.0.armv6l-linux-musleabihf.tar.gz"
[[pigz]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5b2eeed51f52aebe91a5af123c34cc3623b8fb49"
libc = "glibc"
os = "linux"

    [[pigz.download]]
    sha256 = "45a183ca9787f64aed634381b8be337582f97273cbde0f7f470a4626764dc791"
    url = "https://github.com/JuliaBinaryWrappers/pigz_jll.jl/releases/download/pigz-v2.7.0+0/pigz.v2.7.0.armv7l-linux-gnueabihf.tar.gz"
[[pigz]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "03e7798a35d003ff36f47b12a96601255a8b30c2"
libc = "musl"
os = "linux"

    [[pigz.download]]
    sha256 = "fc051aa13019f8e055f39bb896110c58f0975fefab656047e0ffbc1198c28474"
    url = "https://github.com/JuliaBinaryWrappers/pigz_jll.jl/releases/download/pigz-v2.7.0+0/pigz.v2.7.0.armv7l-linux-musleabihf.tar.gz"
[[pigz]]
arch = "i686"
git-tree-sha1 = "1c8fd75633a094b30af8631e6ecce05efa6cf7b5"
libc = "glibc"
os = "linux"

    [[pigz.download]]
    sha256 = "1d79257a558432552fa87dd3b19402807fd4b7040d0baa971a85265c6ae6c562"
    url = "https://github.com/JuliaBinaryWrappers/pigz_jll.jl/releases/download/pigz-v2.7.0+0/pigz.v2.7.0.i686-linux-gnu.tar.gz"
[[pigz]]
arch = "i686"
git-tree-sha1 = "4e53e33b0ca62488578c102fbfa664b1b8f34778"
libc = "musl"
os = "linux"

    [[pigz.download]]
    sha256 = "90f21e44998ec814d698c9178a9d6e95e03426fc7be3d82ab3646f5c87ec6ffd"
    url = "https://github.com/JuliaBinaryWrappers/pigz_jll.jl/releases/download/pigz-v2.7.0+0/pigz.v2.7.0.i686-linux-musl.tar.gz"
[[pigz]]
arch = "i686"
git-tree-sha1 = "73158434f1eeb35e62817f85f91b3d7947a979c9"
os = "windows"

    [[pigz.download]]
    sha256 = "9d382eac84733e457943f18a147b6d322654fb868f4530816c6b3fea2ea04932"
    url = "https://github.com/JuliaBinaryWrappers/pigz_jll.jl/releases/download/pigz-v2.7.0+0/pigz.v2.7.0.i686-w64-mingw32.tar.gz"
[[pigz]]
arch = "powerpc64le"
git-tree-sha1 = "edd0187e9e797cf432d9682e2c72ffbe41348ff6"
libc = "glibc"
os = "linux"

    [[pigz.download]]
    sha256 = "c57ac3aa54325eea7981d982ece158cc1a605c3cb10173b197bfe546c2881e43"
    url = "https://github.com/JuliaBinaryWrappers/pigz_jll.jl/releases/download/pigz-v2.7.0+0/pigz.v2.7.0.powerpc64le-linux-gnu.tar.gz"
[[pigz]]
arch = "x86_64"
git-tree-sha1 = "49bead70fbf298c619aaae5f85b07078f0dc0bff"
os = "macos"

    [[pigz.download]]
    sha256 = "4fa805d4572e2be871abcb6e21ef40f7e9a3b0cc555082406787d2f0f5b2a782"
    url = "https://github.com/JuliaBinaryWrappers/pigz_jll.jl/releases/download/pigz-v2.7.0+0/pigz.v2.7.0.x86_64-apple-darwin.tar.gz"
[[pigz]]
arch = "x86_64"
git-tree-sha1 = "48f36f33e49221cd912a7123adcec592598c8a97"
libc = "glibc"
os = "linux"

    [[pigz.download]]
    sha256 = "07240afc84ae446962148e15cdfeb27a5ad082b2b66f0334ff70e4cd2231fdbb"
    url = "https://github.com/JuliaBinaryWrappers/pigz_jll.jl/releases/download/pigz-v2.7.0+0/pigz.v2.7.0.x86_64-linux-gnu.tar.gz"
[[pigz]]
arch = "x86_64"
git-tree-sha1 = "fa1db1a9cc301d92fe825f5eec7415a25cd246dd"
libc = "musl"
os = "linux"

    [[pigz.download]]
    sha256 = "6abc599720150b3d1fa62c1632cdba4f40ee6a72cfbd0667b38f432125669b4c"
    url = "https://github.com/JuliaBinaryWrappers/pigz_jll.jl/releases/download/pigz-v2.7.0+0/pigz.v2.7.0.x86_64-linux-musl.tar.gz"
[[pigz]]
arch = "x86_64"
git-tree-sha1 = "e96686ebad9b4e8b882efa49e60e36e79541af1c"
os = "freebsd"

    [[pigz.download]]
    sha256 = "3dae9dc5293a7bcb935803b7ab1850affec623ceaf69c26d03bc2dda0326745d"
    url = "https://github.com/JuliaBinaryWrappers/pigz_jll.jl/releases/download/pigz-v2.7.0+0/pigz.v2.7.0.x86_64-unknown-freebsd.tar.gz"
[[pigz]]
arch = "x86_64"
git-tree-sha1 = "3af3623b0e8a80b669c9cfa74f43dbb209a91d54"
os = "windows"

    [[pigz.download]]
    sha256 = "9b771fc7dc20b832e131aa22af3de9ea54fa283c2e77d19bf7976da67453feee"
    url = "https://github.com/JuliaBinaryWrappers/pigz_jll.jl/releases/download/pigz-v2.7.0+0/pigz.v2.7.0.x86_64-w64-mingw32.tar.gz"
